### ISSUE TITLE
Filesystem operations

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/sutrc#3]
- [x] File upload/download handling at server
  More complex requirement. Needs protocol extension. See [foxcpp/filedrop](https://github.com/foxcpp/filedrop).
- [x] Define task types for operations
- [x] File browser in sutcp
- [x] Download/move/delete in sutcp
- [x] File uploading in sutcp
- [x] Implement task types in agent

**Comment by foxcpp** [comment]
See d73bdaa944052132ea0f8d1a0f7c9f436dc22cca.

**Comment by foxcpp** [comment]
I don't know much about Windows permissions. But we definitely have to take care of them when uploading/downloading files. @Hexawolf, can you help me a bit here?

**Comment by Hexawolf** [comment]
Windows does not have a traditional permissions control. Instead, it uses a per-file [Access Control List](https://docs.microsoft.com/en-us/windows/desktop/SecAuthZ/access-control-lists) - a list of [Access Control Entries](https://docs.microsoft.com/en-us/windows/desktop/SecAuthZ/access-control-entries) (feel this bureaucracy). GoLang does not seem to implement any of those WinAPI functions, which makes a good point at the fact that nobody really cares about ACLs in Windows. This is because most of times ACLs are ought to be tuned properly "out of box". However, if you still think that we need to properly control access, here are some points that may either change your mind entirely or at least put this into a long shelf:
* There is no universal way in current application design to know which user is the real user account, which makes protecting information after transmission from local "attackers" nearly impossible for us.
* ACLs are easy to modify if your user is an administrator, which is the majority of cases with Windows-driven PCs.
* If you still wanna mess with that, keep in mind that the real owner of file is going to be Administrator, while in most cases you want file to be accessible by simple user. Thus, you're simply not going to change ACL for file _at all_.
But, well, if you still have plans on messing with this, there's a [package](https://github.com/hectane/go-acl) that makes ACLs work similarly to UNIX permissions for you.

**Comment by foxcpp** [comment]
>keep in mind that the real owner of file is going to be Administrator, while in most cases you want file to be accessible by simple user. Thus, you're simply not going to change ACL for file at all.

So by default files created by admin account are accessible by simple user? Ok, that's what I was worried about.

**Comment by Hexawolf** [comment]
> So by default files created by admin account are accessible by simple user?
If you think about it, this is motivated by Windows design actually. The system easier to work with for everyone, but this gradually decreases security. Maybe they are even right: protecting system from local attacker makes not that much sense since they are already in, they can just reboot it, plug malicious USB and that's all!

Speaking of **why** Administrator, this is related to #5

**Comment by foxcpp** [comment]
Full implementation is in `master` branch. Go check it out.

**Comment by foxcpp** [comment]
Everything seem to work correctly except strange "sharing violation" error I getting on rename/delete, but that's probably because I'm using wine to test agent code. Reopen if something is broken and I didn't noticed.
